version: '3.3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    env_file:
      - .env
    environment:
      bot_token: ${BOT_TOKEN}
    volumes:
      - ./../bot/:/app/
    ports:
      - 5001:8080
    restart: always